<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  <!-- هذا السطر يخفي شاشة الكونسول السوداء -->
    <OutputType>WinExe</OutputType>
    <!-- تفعيل مكتبات واجهات ويندوز -->
    <UseWindowsForms>true</UseWindowsForms>
  <ApplicationIcon>app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Utilities\" />
  </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

</Project>
